---
- hosts: frontend
  become_user: root

  tasks:
  - name: Отключаем SELinux
    selinux:
      state: disabled
  - name: Install Nginx Web Server on RedHat Family
    yum:
      name=nginx
      state=latest
    notify:
      - nginx systemd
  - name: Replace nginx.conf
    copy:
      src=/home/logbox/corsair/virtuals/ansible/git/ansible/nginx.conf
      dest=/etc/nginx/nginx.conf
  - name: Отключение FirewallD
    firewalld:
      port: 8081/tcp
      permanent: true
      state: disabled
  - name: Перезагрузка хостов и ожидание их перезагрузки
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
  - name: restart nginx
    service:
      name: nginx
      state: restarted
- hosts: backend
  become_user: root
  tasks:
   - name: To install NetData
     apt:
        name=netdata
        state=latest
   - name: Replace netdata.conf
     copy:
       src=/home/logbox/corsair/virtuals/ansible/git/ansible/netdata.conf
       dest=/etc/netdata/netdata.conf
   - name: restart netdata
     service:
       name: netdata
       state: restarted

